### PR TITLE
Add cors middleware

### LINKED ISSUE #12: Enable CORS on server

### PR DESCRIPTION
**Pull request by ekelen**
Closes #12

### CODE REVIEW

**Comment by ekelen** [comment]
> It works! ALSO, maybe we should find a way to not need to set response headers in every single handler, seems like that's the goal of using middle-wares, so maybe there's something missing

Yeah. Added.

**Comment by eskombro** [comment]
It works perfectly! The we can remove the line adding header in each handler as it's useless now! But perfect ;)

**Comment by eskombro** [comment]
I did it in a new commit. Also included the 'content-type' header in the same middleware, as we alsways use it. Let me know what you think ;)

**Comment by ekelen** [comment]
Yeah cool, was gonna suggest it but didn't know if you had other content plans :)

**Pull request merged**
